name: Economics and R
description: Economics and R
url: http://skranz.github.io/

markdown: kramdown
# Use the line below to compile on github.io
#pygments: true

# Use the line below to complie locally
highlighter: rouge
